/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cedamus.civilrm.ui.basic.element;


import com.cedamus.civilrm.entity.base.CivilBean;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author Khalid
 */
public class ReferenceFieldPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReferenceFieldPanel
     */
    public ReferenceFieldPanel() {
        initComponents();
    }
    
    
    public ReferenceFieldPanel(int fieldLength,Class clazz) {
        this.fieldLength = fieldLength;
        this.Bean =clazz;
        try
        {
        init();
        }
        catch(Exception er)
        {
            
        }
      }

   public void setLabelText(String txt)
    {
        label.setText(txt);

    }
    public int getFieldLength() {
        return fieldLength;
    }

    public void setFieldLength(int fieldLength) {
        this.fieldLength = fieldLength;
    }

    public JComboBox<CivilBean> getList() {
        return list;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();

        label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(label)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables

     private javax.swing.JComboBox<CivilBean> list;
     
     private int fieldLength;
     long id;

    public long getId() {
        
        return       ((CivilBean)list.getSelectedItem()).getId();
    }
     
     
     
     private Class Bean;
private void init() throws Exception
{
        label = new javax.swing.JLabel();

        List<CivilBean> listBean = ((CivilBean)Class.forName(Bean.getName()).newInstance()).list();
        list = new javax.swing.JComboBox<CivilBean>(listBean.toArray(new CivilBean[listBean.size()]));

        setPreferredSize(new java.awt.Dimension(352, 54));

        label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label.setLabelFor(list);
         label.setFont(new java.awt.Font("Tahoma", 0, 14)); 
         list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, fieldLength, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
   
}

}
