package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1

import com.cedamus.civilrm.entity.base.CivilBean;




/**
 * AutorityAgent generated by hbm2java
 */
public class AutorityAgent extends CivilBean implements java.io.Serializable {


     private long id;
     private String firstName;
     private String lastName;

    public AutorityAgent() {
    }

	
    public AutorityAgent(long id) {
        this.id = id;
    }
    public AutorityAgent(long id, String firstName, String lastName) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Override
    public String getBeanName() {
       return this.getClass().getName();
    }

    @Override
    public String getShownListField() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String[] getVectorShownListField() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String toString() {
        return getFirstName()+" "+getLastName();
    }


    
    


}


