package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CommonLife generated by hbm2java
 */
public class CommonLife  implements java.io.Serializable {


     private long id;
     private String number;
     private String lastName;
     private Date deliveryDate;
     private String motherFullName;
     private String fatherFullName;
     private Date editionDate;
     private Long autorityAgentFk;

    public CommonLife() {
    }

	
    public CommonLife(long id) {
        this.id = id;
    }
    public CommonLife(long id, String number, String lastName, Date deliveryDate, String motherFullName, String fatherFullName, Date editionDate, Long autorityAgentFk) {
       this.id = id;
       this.number = number;
       this.lastName = lastName;
       this.deliveryDate = deliveryDate;
       this.motherFullName = motherFullName;
       this.fatherFullName = fatherFullName;
       this.editionDate = editionDate;
       this.autorityAgentFk = autorityAgentFk;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getMotherFullName() {
        return this.motherFullName;
    }
    
    public void setMotherFullName(String motherFullName) {
        this.motherFullName = motherFullName;
    }
    public String getFatherFullName() {
        return this.fatherFullName;
    }
    
    public void setFatherFullName(String fatherFullName) {
        this.fatherFullName = fatherFullName;
    }
    public Date getEditionDate() {
        return this.editionDate;
    }
    
    public void setEditionDate(Date editionDate) {
        this.editionDate = editionDate;
    }
    public Long getAutorityAgentFk() {
        return this.autorityAgentFk;
    }
    
    public void setAutorityAgentFk(Long autorityAgentFk) {
        this.autorityAgentFk = autorityAgentFk;
    }




}


