package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CorrectRegistration generated by hbm2java
 */
public class CorrectRegistration  implements java.io.Serializable {


     private long id;
     private String number;
     private String actNumber;
     private Integer year;
     private String fullNamee;
     private String birthDate;
     private String birthPlace;
     private String motherFullName;
     private String fatherFullName;
     private String object;
     private String errataName;
     private String correctName;
     private Date editionDate;

    public CorrectRegistration() {
    }

	
    public CorrectRegistration(long id) {
        this.id = id;
    }
    public CorrectRegistration(long id, String number, String actNumber, Integer year, String fullNamee, String birthDate, String birthPlace, String motherFullName, String fatherFullName, String object, String errataName, String correctName, Date editionDate) {
       this.id = id;
       this.number = number;
       this.actNumber = actNumber;
       this.year = year;
       this.fullNamee = fullNamee;
       this.birthDate = birthDate;
       this.birthPlace = birthPlace;
       this.motherFullName = motherFullName;
       this.fatherFullName = fatherFullName;
       this.object = object;
       this.errataName = errataName;
       this.correctName = correctName;
       this.editionDate = editionDate;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getActNumber() {
        return this.actNumber;
    }
    
    public void setActNumber(String actNumber) {
        this.actNumber = actNumber;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getFullNamee() {
        return this.fullNamee;
    }
    
    public void setFullNamee(String fullNamee) {
        this.fullNamee = fullNamee;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }
    public String getMotherFullName() {
        return this.motherFullName;
    }
    
    public void setMotherFullName(String motherFullName) {
        this.motherFullName = motherFullName;
    }
    public String getFatherFullName() {
        return this.fatherFullName;
    }
    
    public void setFatherFullName(String fatherFullName) {
        this.fatherFullName = fatherFullName;
    }
    public String getObject() {
        return this.object;
    }
    
    public void setObject(String object) {
        this.object = object;
    }
    public String getErrataName() {
        return this.errataName;
    }
    
    public void setErrataName(String errataName) {
        this.errataName = errataName;
    }
    public String getCorrectName() {
        return this.correctName;
    }
    
    public void setCorrectName(String correctName) {
        this.correctName = correctName;
    }
    public Date getEditionDate() {
        return this.editionDate;
    }
    
    public void setEditionDate(Date editionDate) {
        this.editionDate = editionDate;
    }




}


