package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ElementaryCommonLife generated by hbm2java
 */
public class ElementaryCommonLife  implements java.io.Serializable {


     private long id;
     private Long commonLifeFk;
     private String fullName;
     private Date birthDate;
     private String birthPlace;

    public ElementaryCommonLife() {
    }

	
    public ElementaryCommonLife(long id) {
        this.id = id;
    }
    public ElementaryCommonLife(long id, Long commonLifeFk, String fullName, Date birthDate, String birthPlace) {
       this.id = id;
       this.commonLifeFk = commonLifeFk;
       this.fullName = fullName;
       this.birthDate = birthDate;
       this.birthPlace = birthPlace;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getCommonLifeFk() {
        return this.commonLifeFk;
    }
    
    public void setCommonLifeFk(Long commonLifeFk) {
        this.commonLifeFk = commonLifeFk;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }




}


