package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private long id;
     private String firstNameLatin;
     private String lastNameLatin;
     private String firstNameArabic;
     private String lastNameArabic;
     private String gender;
     private Date birthDate;
     private String hijirBirthDate;
     private String birthPlace;
     private String fullNameArabic;
     private String fullNameLatin;
     private String professionLatin;
     private String professionArabic;
     private String adressLatin;
     private String adressArabic;
     private Long relativeFk;

    public Person() {
    }

	
    public Person(long id) {
        this.id = id;
    }
    public Person(long id, String firstNameLatin, String lastNameLatin, String firstNameArabic, String lastNameArabic, String gender, Date birthDate, String hijirBirthDate, String birthPlace, String fullNameArabic, String fullNameLatin, String professionLatin, String professionArabic, String adressLatin, String adressArabic, Long relativeFk) {
       this.id = id;
       this.firstNameLatin = firstNameLatin;
       this.lastNameLatin = lastNameLatin;
       this.firstNameArabic = firstNameArabic;
       this.lastNameArabic = lastNameArabic;
       this.gender = gender;
       this.birthDate = birthDate;
       this.hijirBirthDate = hijirBirthDate;
       this.birthPlace = birthPlace;
       this.fullNameArabic = fullNameArabic;
       this.fullNameLatin = fullNameLatin;
       this.professionLatin = professionLatin;
       this.professionArabic = professionArabic;
       this.adressLatin = adressLatin;
       this.adressArabic = adressArabic;
       this.relativeFk = relativeFk;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getFirstNameLatin() {
        return this.firstNameLatin;
    }
    
    public void setFirstNameLatin(String firstNameLatin) {
        this.firstNameLatin = firstNameLatin;
    }
    public String getLastNameLatin() {
        return this.lastNameLatin;
    }
    
    public void setLastNameLatin(String lastNameLatin) {
        this.lastNameLatin = lastNameLatin;
    }
    public String getFirstNameArabic() {
        return this.firstNameArabic;
    }
    
    public void setFirstNameArabic(String firstNameArabic) {
        this.firstNameArabic = firstNameArabic;
    }
    public String getLastNameArabic() {
        return this.lastNameArabic;
    }
    
    public void setLastNameArabic(String lastNameArabic) {
        this.lastNameArabic = lastNameArabic;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getHijirBirthDate() {
        return this.hijirBirthDate;
    }
    
    public void setHijirBirthDate(String hijirBirthDate) {
        this.hijirBirthDate = hijirBirthDate;
    }
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }
    public String getFullNameArabic() {
        return this.fullNameArabic;
    }
    
    public void setFullNameArabic(String fullNameArabic) {
        this.fullNameArabic = fullNameArabic;
    }
    public String getFullNameLatin() {
        return this.fullNameLatin;
    }
    
    public void setFullNameLatin(String fullNameLatin) {
        this.fullNameLatin = fullNameLatin;
    }
    public String getProfessionLatin() {
        return this.professionLatin;
    }
    
    public void setProfessionLatin(String professionLatin) {
        this.professionLatin = professionLatin;
    }
    public String getProfessionArabic() {
        return this.professionArabic;
    }
    
    public void setProfessionArabic(String professionArabic) {
        this.professionArabic = professionArabic;
    }
    public String getAdressLatin() {
        return this.adressLatin;
    }
    
    public void setAdressLatin(String adressLatin) {
        this.adressLatin = adressLatin;
    }
    public String getAdressArabic() {
        return this.adressArabic;
    }
    
    public void setAdressArabic(String adressArabic) {
        this.adressArabic = adressArabic;
    }
    public Long getRelativeFk() {
        return this.relativeFk;
    }
    
    public void setRelativeFk(Long relativeFk) {
        this.relativeFk = relativeFk;
    }




}


