package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Register generated by hbm2java
 */
public class Register  implements java.io.Serializable {


     private long id;
     private Integer year;
     private Integer hijirYear;
     private Long registerTypeFk;
     private Integer firstActNumber;
     private Integer pageCount;
     private Long trinbunalFk;
     private String procurror;
     private Date signDate;
     private String signHijirDate;

    public Register() {
    }

	
    public Register(long id) {
        this.id = id;
    }
    public Register(long id, Integer year, Integer hijirYear, Long registerTypeFk, Integer firstActNumber, Integer pageCount, Long trinbunalFk, String procurror, Date signDate, String signHijirDate) {
       this.id = id;
       this.year = year;
       this.hijirYear = hijirYear;
       this.registerTypeFk = registerTypeFk;
       this.firstActNumber = firstActNumber;
       this.pageCount = pageCount;
       this.trinbunalFk = trinbunalFk;
       this.procurror = procurror;
       this.signDate = signDate;
       this.signHijirDate = signHijirDate;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Integer getHijirYear() {
        return this.hijirYear;
    }
    
    public void setHijirYear(Integer hijirYear) {
        this.hijirYear = hijirYear;
    }
    public Long getRegisterTypeFk() {
        return this.registerTypeFk;
    }
    
    public void setRegisterTypeFk(Long registerTypeFk) {
        this.registerTypeFk = registerTypeFk;
    }
    public Integer getFirstActNumber() {
        return this.firstActNumber;
    }
    
    public void setFirstActNumber(Integer firstActNumber) {
        this.firstActNumber = firstActNumber;
    }
    public Integer getPageCount() {
        return this.pageCount;
    }
    
    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }
    public Long getTrinbunalFk() {
        return this.trinbunalFk;
    }
    
    public void setTrinbunalFk(Long trinbunalFk) {
        this.trinbunalFk = trinbunalFk;
    }
    public String getProcurror() {
        return this.procurror;
    }
    
    public void setProcurror(String procurror) {
        this.procurror = procurror;
    }
    public Date getSignDate() {
        return this.signDate;
    }
    
    public void setSignDate(Date signDate) {
        this.signDate = signDate;
    }
    public String getSignHijirDate() {
        return this.signHijirDate;
    }
    
    public void setSignHijirDate(String signHijirDate) {
        this.signHijirDate = signHijirDate;
    }




}


