package com.cedamus.civilrm.entity;
// Generated Feb 8, 2017 9:36:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private long id;
     private String number;
     private String lastName;
     private Date deliveryDate;
     private String firstName;
     private String familyName;
     private Date birthDate;
     private String birthPlace;
     private String motherFullName;
     private String fatherFullName;
     private Date editionDate;
     private Long autorityAgentFk;

    public Registration() {
    }

	
    public Registration(long id) {
        this.id = id;
    }
    public Registration(long id, String number, String lastName, Date deliveryDate, String firstName, String familyName, Date birthDate, String birthPlace, String motherFullName, String fatherFullName, Date editionDate, Long autorityAgentFk) {
       this.id = id;
       this.number = number;
       this.lastName = lastName;
       this.deliveryDate = deliveryDate;
       this.firstName = firstName;
       this.familyName = familyName;
       this.birthDate = birthDate;
       this.birthPlace = birthPlace;
       this.motherFullName = motherFullName;
       this.fatherFullName = fatherFullName;
       this.editionDate = editionDate;
       this.autorityAgentFk = autorityAgentFk;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getFamilyName() {
        return this.familyName;
    }
    
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getBirthPlace() {
        return this.birthPlace;
    }
    
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }
    public String getMotherFullName() {
        return this.motherFullName;
    }
    
    public void setMotherFullName(String motherFullName) {
        this.motherFullName = motherFullName;
    }
    public String getFatherFullName() {
        return this.fatherFullName;
    }
    
    public void setFatherFullName(String fatherFullName) {
        this.fatherFullName = fatherFullName;
    }
    public Date getEditionDate() {
        return this.editionDate;
    }
    
    public void setEditionDate(Date editionDate) {
        this.editionDate = editionDate;
    }
    public Long getAutorityAgentFk() {
        return this.autorityAgentFk;
    }
    
    public void setAutorityAgentFk(Long autorityAgentFk) {
        this.autorityAgentFk = autorityAgentFk;
    }




}


