/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cedamus.civilrm.ui;

import com.cedamus.civilrm.entity.base.CivilBean;
import com.cedamus.civilrm.ui.basic.panel.CivilEditPanel;
import com.cedamus.civilrm.ui.basic.panel.CivilListPanel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Khalid
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        certificateMenu = new javax.swing.JMenu();
        NameConformityCertificateMenu = new javax.swing.JMenu();
        NameConformityCertificateListMenu = new javax.swing.JMenuItem();
        AddNewNameConformityCertificateMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        MainPanel.setBackground(new java.awt.Color(255, 51, 51));
        MainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainPanel);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("FILE")); // NOI18N
        jMenuBar1.add(jMenu1);

        certificateMenu.setText(bundle.getString("CERTIFICATS")); // NOI18N

        NameConformityCertificateMenu.setText(bundle.getString("NAMECONFORMITYCERTIFICATEMENU")); // NOI18N

        NameConformityCertificateListMenu.setText(bundle.getString("NAMECONFORMITYCERTIFICATELISTMENU")); // NOI18N
        NameConformityCertificateListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameConformityCertificateListMenuActionPerformed(evt);
            }
        });
        NameConformityCertificateMenu.add(NameConformityCertificateListMenu);

        AddNewNameConformityCertificateMenu.setText(bundle.getString("add.new")); // NOI18N
        AddNewNameConformityCertificateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewNameConformityCertificateMenuActionPerformed(evt);
            }
        });
        NameConformityCertificateMenu.add(AddNewNameConformityCertificateMenu);

        certificateMenu.add(NameConformityCertificateMenu);

        jMenuBar1.add(certificateMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewNameConformityCertificateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewNameConformityCertificateMenuActionPerformed

         showInMainPanel("edit", "BeanName");
    }//GEN-LAST:event_AddNewNameConformityCertificateMenuActionPerformed

    private void NameConformityCertificateListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameConformityCertificateListMenuActionPerformed
        showInMainPanel("list", "BeanName");
      
    }//GEN-LAST:event_NameConformityCertificateListMenuActionPerformed

    public void showInMainPanel(String type, String BeanName)
    {
        
          MainPanel.removeAll();

        MainPanel.repaint();
        MainPanel.revalidate();
//        if ("list".equalsIgnoreCase(type))
//        {
//               //  CivilListPanel cp= new CivilListPanel(this);
//    //    MainPanel.add(cp);   
//        }
//        else
//        {
//             CivilEditPanel cp= new CivilEditPanel( new com.cedamus.civilrm.entity.NameConformity());
//        MainPanel.add(cp);
//        }

        
        MainPanel.repaint();
        MainPanel.revalidate();
    }
    
    
        public void showInMainPanel(CivilBean bean)
    {
        
          MainPanel.removeAll();

        MainPanel.repaint();
        MainPanel.revalidate();

        
       
       bean=(CivilBean) bean.load();

        JOptionPane.showMessageDialog(null, bean.getId());
    //    CivilEditPanel cp= new CivilEditPanel(bean);
    //    MainPanel.add(cp);
       

        
        MainPanel.repaint();
        MainPanel.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNewNameConformityCertificateMenu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenuItem NameConformityCertificateListMenu;
    private javax.swing.JMenu NameConformityCertificateMenu;
    private javax.swing.JMenu certificateMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    public JPanel getMainPanel() {
        return MainPanel;
    }

    public void setMainPanel(JPanel MainPanel) {
        this.MainPanel = MainPanel;
    }




}
